# Generated by Django 6.0.5 on 2026-06-02 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemapextraction',
            name='ip_address',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitemapextraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
